baseURL: "/"
DefaultContentLanguage: en
title: Brightest Days Spray Foam Co.
description: Spray Foam Insulation Services in Tofino, Ucluelet & Port Alberni. Because Energy Efficient Homes Are More Valuable. Get a FREE Consultation Today.

menu:
      main:
        - name: Home
          url: '/'
          weight: 1
        - name: About
          url: '#about'
          weight: 2
        - name: Menu
          url: '#menu'
          weight: 3
        - name: Photos
          url: '#Photos'
          weight: 4
        - name: Reviews
          url: '#Photos'
          weight: 5
        - name: Contact
          url: '#contact'
          weight: 6

params:
    name: 'Brightest Days Spray Foam Co.'
    showLanguageSelector: false #true if bilingual site - false if unilingua
    usebasin: '' #endpoint for forms
    googlemap: '' # Map code of Google
    gtm: ''
    imagekit_base_url: "https://ik.imagekit.io/supersonicsites/Westcoast_Salty_Buns/"
    hours:
        hour1en: 'Mon to Fri - 9:00-17:00' #Footer Hours Line #1
        hour2en: 'Sat - On Demand' #Footer Hours Line #2
        hour3en: 'Sun - On Demand' #Footer Hours Line #3
    social:
        facebook: ''
        twitter: ''
        pinterest: ''
        instagram: ''
        linkedin: ''
    schema:
        type: ProfessionalService
        priceRange: $$$
        reservation: 'false'
        openinghour: 'Mo-Fr 9:00-17:00'
        logo: "img/logo.png"
        logofooter: "img/logo.png"
        logo: "logo-vertical_Q9u2mUs5X.jpg"
        og: "img/og.jpg"
        address: 1356 Pine Rd.
        address2: ''
        city: Ucluelet
        region: BC
        country: Canada
        postalcode: V0R 3A0
        phone: +1-250-720-7610 
        email: info@brightestdays.ca

enableRobotsTXT: true
disableAliases: true
disableKinds:
  - taxonomy
  - taxonomyTerm

sitemap:
  changefreq: monthly
  filename: sitemap.xml

imaging:
  resampleFilter: box
  quality: 85
  anchor: smart