baseURL: "https://www.westcoastsaltybuns.com/"
DefaultContentLanguage: en
title: West Coast Salty Buns
description: Ukee's Coolest Winnebago Food Truck. Serving Up Fresh Top Quality Bites, Burritos, Bacos & Bowls.

menu:
      main:
        - name: About
          url: '#section3'
          weight: 2
        - name: Menu
          url: '#menu'
          weight: 3
        - name: Photos
          url: '#section4'
          weight: 4
        - name: Reviews
          url: '#section6'
          weight: 5
        - name: Contact
          url: '#contact'
          weight: 6

params:
    name: 'West Coast Salty Buns'
    showLanguageSelector: false #true if bilingual site - false if unilingua
    usebasin: 'https://usebasin.com/f/1daf74fdc826' #endpoint for forms
    googlemap: '' # Map code of Google
    gtm: 'GTM-PVL3WCQ'
    imagekit_base_url: "https://ik.imagekit.io/supersonicsites/Westcoast_Salty_Buns/"
    hours:
        hour1en: 'Mon to Fri - 12:00-7:00' #Footer Hours Line #1
        hour2en: 'Sat - 12:00-7:00' #Footer Hours Line #2
        hour3en: 'Sun - 12:00-7:00' #Footer Hours Line #3
    social:
        facebook: ''
        twitter: ''
        pinterest: ''
        instagram: 'https://www.instagram.com/westcoastsalty_buns_'
        linkedin: ''
    schema:
        type: Restaurant
        priceRange: $$$
        reservation: 'false'
        openinghour: 'Tu-Sa 12:00-19:00'
        logo: "img/logo.png"
        logofooter: "img/logo.png"
        logo: "logo-vertical_Q9u2mUs5X.jpg"
        og: "https://ik.imagekit.io/supersonicsites/Westcoast_Salty_Buns/tr:ar-16-9,w-1600,/saltybuns-19_jXuCrehKD.JPG"
        address: 1708 Peninsula Road
        address2: ''
        city: Ucluelet
        region: BC
        country: Canada
        postalcode: V0R 3A0
        phone: +1-250-726-6150
        email: westcoastsaltybuns@gmail.com

enableRobotsTXT: true
disableAliases: true
disableKinds:
  - taxonomy
  - taxonomyTerm

sitemap:
  changefreq: monthly
  filename: sitemap.xml

imaging:
  resampleFilter: box
  quality: 85
  anchor: smart