[build]
publish = "public"
command = "hugo --gc --minify"

[[redirects]]
  from = "https://saltybuns.netlify.app/"
  to = "https://www.westcoastsaltybuns.com/"
  status = 301
  force = true #COMMENT: ensure that we always redirect

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404